version: 2

models:

  - name: Sales_Recruitment
    description: "Sales occured in the year 2022 and 2023, comprises information about the clients, orders, products, transactions and turnover w.r.t time"
    columns:
      - name: date_date, 
              client_id,
              transaction_id,
              products_id,
              turnover,
              qty
        description: "The primary key for this table is client_id"
        tests:
          - not_null
  
  - name: Orders_Recruitment
    description: "Orders occured in the year 2022 and 2023, comprises information about the clients and orders"
    columns:
      - name: date_date, 
              customer_id,
              orders_id,
              CA_ht
        description: "The primary key for this table is customer_id"
        tests:
          - not_null

  - name: orders_quantity (exercise 4)
    description: "All orders in the year 2022 and 2023; this table is similar to orders with an additional column: the qty_product column that gives the quantity of products in the order, for all orders in 2022 and 2023"
    columns:
      - name: date_date, 
              customer_id,
              orders_id,
              ca_ht,
              qty_product
        
        tests:
          - not_null 

  - name: orders_segmentation (exercise 5/6)
    description: "Orders are segmented into 3 groups:	New: it's the 1st order of the customer (client_id) in the past 12 months. In the 12 months prior to this order, the customer did not place any orders; Returning: it's between the 2nd and the 4th order of the customer in the past 12 months. In the 12 months prior to this order, the customer had already placed between 1 and 3 orders; VIP: it's the 5th or more order of the customer in the past 12 months. In the 12 months prior to this order, the customer had already placed at least 4 orders or more"
    columns:
      - name: date_date, 
              customer_id,
              orders_id,
              CA_ht,
              orders_segmentation
        
        tests:
          - not_null  

  - name: Exercise 1
    description: "Number of orders in the year 2023"
    columns:
      - name: total_orders
        tests:
          - not_null         

  - name: Exercise 2
    description: "Number of orders per month in the year 2023"
    columns:
      - name: Month,
              orders_per_month
        tests:
          - not_null  

  - name: Exercise 3
    description: "Average number of products per order for each month of the year 2023"
    columns:
      - name: Month,
              average_products_per_order
        tests:
          - not_null